/* SPA product data — all 5 product pages bundled for client-side navigation */
window.SPA_DATA = {};

window.SPA_DATA['jackets.html'] = {
  heading: 'Jackets',
  products: [
  {
    short: 'Siena Quilt Coat',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted coat</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted coat design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><div class="pm-desc-text">One existing bound twin-size quilt (minimum 65" x 85"). Upcycle a thrifted quilt or vintage blanket into a unique, one-of-a-kind coat.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/product 1/1.webp','assets/products/product 1/2.webp','assets/products/product 1/3.webp','assets/products/product 1/4.webp','assets/products/product 1/5.webp','assets/products/product 1/6.webp','assets/products/product 1/7.webp'],
    url: 'https://www.etsy.com/listing/4430351753/siena-quilt-coat-sewing-pattern-beginner'
  },
  {
    short: 'Hooded Quilted Jacket',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted jacket design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/product 2/1.webp','assets/products/product 2/2.webp','assets/products/product 2/3.webp','assets/products/product 2/4.webp','assets/products/product 2/5.webp','assets/products/product 2/6.webp','assets/products/product 2/7.webp'],
    url: 'https://www.etsy.com/listing/4411882487/hooded-quilted-jacket-sewing-pattern'
  },
  {
    short: 'Beginner Hooded Jacket',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted jacket design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 3/1.webp','assets/products/Product 3/2.webp','assets/products/Product 3/3.webp','assets/products/Product 3/4.webp','assets/products/Product 3/5.webp','assets/products/Product 3/6.webp','assets/products/Product 3/7.webp','assets/products/Product 3/8.webp'],
    url: 'https://www.etsy.com/listing/4430353699/beginner-hooded-quilted-jacket-sewing'
  },
  {
    short: 'Florence Quilt Coat',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted coat</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted coat design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><div class="pm-desc-text">One existing bound twin-size quilt (minimum 65" x 85"). Upcycle a thrifted quilt or vintage blanket into a unique, one-of-a-kind coat.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 4/1.webp','assets/products/Product 4/2.webp','assets/products/Product 4/3.webp','assets/products/Product 4/4.webp','assets/products/Product 4/5.webp','assets/products/Product 4/6.webp','assets/products/Product 4/7.webp','assets/products/Product 4/8.webp'],
    url: 'https://www.etsy.com/listing/4415566335/florence-quilt-coat-beginner-sewing'
  },
  {
    short: 'Blossom Quilt Coat',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted jacket design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 5/1.webp','assets/products/Product 5/2.webp','assets/products/Product 5/3.webp','assets/products/Product 5/4.webp','assets/products/Product 5/5.webp','assets/products/Product 5/6.webp','assets/products/Product 5/7.webp','assets/products/Product 5/8.webp'],
    url: 'https://www.etsy.com/listing/4432059064/blossom-quilt-coat-sewing-pattern'
  },
  {
    short: 'Rosa Quilted Jacket',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li><li>Exclusive video tutorial providing visual step-by-step guidance</li><li>Printable pattern pieces marked clearly for easy cutting and assembly</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted jacket design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><ul class="pm-desc-list"><li>Fabric 150cm wide: 120-205cm</li><li>Bias Band: approximately 8-10 meters</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 6/1.webp','assets/products/Product 6/2.webp','assets/products/Product 6/3.webp','assets/products/Product 6/4.webp','assets/products/Product 6/5.webp','assets/products/Product 6/6.webp'],
    url: 'https://www.etsy.com/listing/4431240739/rosa-quilted-jacket-sewing-pattern'
  },
  {
    short: 'Laurel Crop Jacket',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted jacket design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 7/1.webp','assets/products/Product 7/2.webp','assets/products/Product 7/3.webp','assets/products/Product 7/4.webp','assets/products/Product 7/5.webp','assets/products/Product 7/6.webp','assets/products/Product 7/7.webp'],
    url: 'https://www.etsy.com/listing/4430346985/laurel-crop-jacket-sewing-pattern'
  },
  {
    short: 'Funnel Neck Jacket',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted jacket design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 8/1.webp','assets/products/Product 8/2.webp','assets/products/Product 8/3.webp','assets/products/Product 8/4.webp','assets/products/Product 8/5.webp','assets/products/Product 8/6.webp','assets/products/Product 8/8.webp'],
    url: 'https://www.etsy.com/listing/4430351399/funnel-neck-jacket-sewing-pattern'
  },
  {
    short: 'Hooded Quilted Jacket II',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted jacket design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 9/1.webp','assets/products/Product 9/2.webp','assets/products/Product 9/3.webp','assets/products/Product 9/4.webp','assets/products/Product 9/5.webp','assets/products/Product 9/6.webp','assets/products/Product 9/7.webp','assets/products/Product 9/8.webp','assets/products/Product 9/9.webp'],
    url: 'https://www.etsy.com/listing/4431757951/hooded-quilted-jacket-sewing-pattern'
  },
  {
    short: 'Nora Quilt Coat',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted coat</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted coat design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><div class="pm-desc-text">One existing bound twin-size quilt (minimum 65" x 85"). Upcycle a thrifted quilt or vintage blanket into a unique, one-of-a-kind coat.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 10/1.webp','assets/products/Product 10/2.webp','assets/products/Product 10/3.webp','assets/products/Product 10/4.webp','assets/products/Product 10/5.webp','assets/products/Product 10/6.webp','assets/products/Product 10/7.webp','assets/products/Product 10/8.webp','assets/products/Product 10/9.webp'],
    url: 'https://www.etsy.com/listing/4432057290/nora-quilt-coat-sewing-pattern-beginner'
  },
  {
    short: 'Lirio Quilted Jacket',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted jacket design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 13/1.webp','assets/products/Product 13/2.webp','assets/products/Product 13/3.webp','assets/products/Product 13/4.webp','assets/products/Product 13/5.webp','assets/products/Product 13/6.webp','assets/products/Product 13/7.webp','assets/products/Product 13/8.webp','assets/products/Product 13/9.webp'],
    url: 'https://www.etsy.com/listing/4431772326/lirio-quilted-jacket-sewing-pattern'
  },
  {
    short: 'Wool Jacket',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li><li>Printable pattern pieces marked clearly for easy cutting and assembly</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted jacket design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><div class="pm-desc-text">Medium to heavy coat fabrics such as wool blends, bouclé, tweed, or other structured synthetics. Seam allowance already added: 1 cm.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 17/1.webp','assets/products/Product 17/2.webp','assets/products/Product 17/3.webp','assets/products/Product 17/4.webp','assets/products/Product 17/5.webp','assets/products/Product 17/6.webp','assets/products/Product 17/7.webp','assets/products/Product 17/8.webp','assets/products/Product 17/9.webp'],
    url: 'https://www.etsy.com/listing/4432054776/jacket-sewing-pattern-beginner-friendly'
  },
  {
    short: 'Mariner Quilt Coat',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted coat</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted coat design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><div class="pm-desc-text">One existing bound twin-size quilt (minimum 65" x 85"). Upcycle a thrifted quilt or vintage blanket into a unique, one-of-a-kind coat.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 18/1.webp','assets/products/Product 18/2.webp','assets/products/Product 18/3.webp','assets/products/Product 18/4.webp','assets/products/Product 18/5.webp','assets/products/Product 18/6.webp','assets/products/Product 18/7.webp','assets/products/Product 18/8.webp'],
    url: 'https://www.etsy.com/listing/4446701330/mariner-quilt-coat-sewing-pattern'
  },
  {
    short: 'Siena Quilted Coat',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted coat</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted coat design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><div class="pm-desc-text">One existing bound twin-size quilt (minimum 65" x 85"). Upcycle a thrifted quilt or vintage blanket into a unique, one-of-a-kind coat.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 19/1.webp','assets/products/Product 19/2.webp','assets/products/Product 19/3.webp','assets/products/Product 19/4.webp','assets/products/Product 19/5.webp','assets/products/Product 19/6.webp','assets/products/Product 19/7.webp'],
    url: 'https://www.etsy.com/listing/4430370932/quilted-coat-sewing-pattern-siena-jacket'
  },
  {
    short: 'Valentine Quilted Jacket',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted jacket design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 23/1.webp','assets/products/Product 23/2.webp','assets/products/Product 23/3.webp','assets/products/Product 23/4.webp','assets/products/Product 23/5.webp','assets/products/Product 23/6.webp','assets/products/Product 23/7.webp','assets/products/Product 23/8.webp'],
    url: 'https://www.etsy.com/listing/4451580504/valentine-quilted-jacket-sewing-pattern'
  },
  {
    short: 'Sunset Patchwork Coat',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted coat</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted coat design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><div class="pm-desc-text">One existing bound twin-size quilt (minimum 65" x 85"). Upcycle a thrifted quilt or vintage blanket into a unique, one-of-a-kind coat.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 26/1.webp','assets/products/Product 26/2.webp','assets/products/Product 26/3.webp','assets/products/Product 26/4.webp','assets/products/Product 26/5.webp','assets/products/Product 26/6.webp','assets/products/Product 26/7.webp','assets/products/Product 26/8.webp','assets/products/Product 26/9.webp'],
    url: 'https://www.etsy.com/listing/4431133729/sunset-patchwork-coat-sewing-pattern'
  },
  {
    short: 'Quilted Jacket',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted jacket design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 27/1.webp','assets/products/Product 27/2.webp','assets/products/Product 27/3.webp','assets/products/Product 27/4.webp','assets/products/Product 27/5.webp','assets/products/Product 27/6.webp','assets/products/Product 27/7.webp','assets/products/Product 27/8.webp'],
    url: 'https://www.etsy.com/listing/4431813149/quilted-jacket-sewing-pattern-beginner'
  },
  {
    short: 'Haven Quilted Jacket',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted jacket design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 29/1.webp','assets/products/Product 29/2.webp','assets/products/Product 29/3.webp','assets/products/Product 29/4.webp','assets/products/Product 29/5.webp','assets/products/Product 29/6.webp','assets/products/Product 29/7.webp','assets/products/Product 29/8.webp'],
    url: 'https://www.etsy.com/listing/4482010284/haven-quilted-jacket-sewing-pattern'
  },
  {
    short: 'Funnel Neck Jacket II',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly quilted jacket design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 30/1.webp','assets/products/Product 30/2.webp','assets/products/Product 30/3.webp','assets/products/Product 30/4.webp','assets/products/Product 30/5.webp','assets/products/Product 30/6.webp','assets/products/Product 30/7.webp','assets/products/Product 30/8.webp'],
    url: 'https://www.etsy.com/listing/4432130828/funnel-neck-jacket-sewing-pattern'
  },
  {
    short: 'Cloud Crop Cardigan',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the crop knit cardigan</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly knit cardigan design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Knit yarn such as Wool or Wool Blends, Acrylic Yarn, Cotton Yarn, or any medium-to-thick yarn suitable for knitting a jacket or cardigan.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 36/1.webp','assets/products/Product 36/2.webp','assets/products/Product 36/3.webp','assets/products/Product 36/4.webp','assets/products/Product 36/5.webp','assets/products/Product 36/6.webp','assets/products/Product 36/8.webp'],
    url: 'https://www.etsy.com/listing/4444193383/cloud-crop-cardigan-sewing-pattern'
  },
  {
    short: 'Siena Quilt Coat II',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted coat</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><div class="pm-desc-text">One existing bound twin-size quilt (minimum 65" x 85"). Upcycle a thrifted quilt or vintage blanket into a unique, one-of-a-kind coat.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 11/1.webp','assets/products/Product 11/2.webp','assets/products/Product 11/3.webp','assets/products/Product 11/4.webp','assets/products/Product 11/5.webp','assets/products/Product 11/6.webp','assets/products/Product 11/7.webp','assets/products/Product 11/8.webp','assets/products/Product 11/9.webp'],
    url: 'https://www.etsy.com/listing/4430343668/siena-quilt-coat-sewing-pattern-beginner'
  },
  {
    short: 'Siena Quilt Coat III',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted coat</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><div class="pm-desc-text">One existing bound twin-size quilt (minimum 65" x 85"). Upcycle a thrifted quilt or vintage blanket into a unique, one-of-a-kind coat.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 12/1.webp','assets/products/Product 12/2.webp','assets/products/Product 12/3.webp','assets/products/Product 12/4.webp','assets/products/Product 12/5.webp','assets/products/Product 12/6.webp','assets/products/Product 12/7.webp','assets/products/Product 12/8.webp'],
    url: 'https://www.etsy.com/listing/4430351753/siena-quilt-coat-sewing-pattern-beginner'
  },
  {
    short: 'Laurel Crop Jacket II',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 21/1.webp','assets/products/Product 21/2.webp','assets/products/Product 21/3.webp','assets/products/Product 21/4.webp','assets/products/Product 21/5.webp','assets/products/Product 21/6.webp','assets/products/Product 21/7.webp'],
    url: 'https://www.etsy.com/listing/4468105879/wool-jacket-sewing-pattern-beginner'
  },
  {
    short: 'Hooded Jacket III',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 22/1.webp','assets/products/Product 22/2.webp','assets/products/Product 22/3.webp','assets/products/Product 22/4.webp','assets/products/Product 22/5.webp','assets/products/Product 22/6.webp','assets/products/Product 22/7.webp'],
    url: 'https://www.etsy.com/listing/4431142828/hooded-quilted-jacket-sewing-pattern'
  },
  {
    short: 'Artful Quilted Jacket',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 24/1.webp','assets/products/Product 24/2.webp','assets/products/Product 24/3.webp','assets/products/Product 24/4.webp','assets/products/Product 24/5.webp','assets/products/Product 24/6.webp','assets/products/Product 24/7.webp','assets/products/Product 24/8.webp'],
    url: 'https://www.etsy.com/listing/4447656918/artful-quilted-jacket-sewing-pattern'
  },
  {
    short: 'Blossom Quilt Coat II',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted coat</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 25/1.webp','assets/products/Product 25/2.webp','assets/products/Product 25/3.webp','assets/products/Product 25/4.webp','assets/products/Product 25/5.webp','assets/products/Product 25/6.webp','assets/products/Product 25/7.webp','assets/products/Product 25/8.webp'],
    url: 'https://www.etsy.com/listing/4432060364/blossom-quilt-coat-sewing-pattern'
  },
  {
    short: 'Rosa Quilted Jacket II',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 28/1.webp','assets/products/Product 28/2.webp','assets/products/Product 28/3.webp','assets/products/Product 28/4.webp','assets/products/Product 28/5.webp','assets/products/Product 28/6.webp','assets/products/Product 28/7.webp','assets/products/Product 28/8.webp','assets/products/Product 28/9.webp'],
    url: 'https://www.etsy.com/listing/4431242531/rosa-quilted-jacket-sewing-pattern'
  },
  {
    short: 'Nora Quilt Coat II',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted coat</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><div class="pm-desc-text">One existing bound twin-size quilt (minimum 65" x 85"). Upcycle a thrifted quilt or vintage blanket into a unique, one-of-a-kind coat.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 31/1.webp','assets/products/Product 31/2.webp','assets/products/Product 31/3.webp','assets/products/Product 31/4.webp','assets/products/Product 31/5.webp','assets/products/Product 31/6.webp','assets/products/Product 31/7.webp','assets/products/Product 31/8.webp'],
    url: 'https://www.etsy.com/listing/4430363418/nora-quilt-coat-sewing-pattern-beginner'
  },
  {
    short: 'Laurel Crop Jacket III',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 32/1.webp','assets/products/Product 32/2.webp','assets/products/Product 32/3.webp','assets/products/Product 32/4.webp','assets/products/Product 32/5.webp','assets/products/Product 32/6.webp','assets/products/Product 32/7.webp'],
    url: 'https://www.etsy.com/listing/4431252432/laurel-crop-jacket-sewing-pattern'
  },
  {
    short: 'Quilted Jacket II',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Pre-Quilted Cotton, Nylon or Polyester, Denim, Wool or Wool Blends, or Velvet or Velour.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 33/1.webp','assets/products/Product 33/2.webp','assets/products/Product 33/3.webp','assets/products/Product 33/4.webp','assets/products/Product 33/5.webp','assets/products/Product 33/6.webp','assets/products/Product 33/7.webp','assets/products/Product 33/8.webp'],
    url: 'https://www.etsy.com/listing/4420433813/quilted-jacket-sewing-pattern-beginner'
  },
  {
    short: 'Florence Quilt Coat II',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted coat</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><div class="pm-desc-text">One existing bound twin-size quilt (minimum 65" x 85"). Upcycle a thrifted quilt or vintage blanket into a unique, one-of-a-kind coat.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 34/1.webp','assets/products/Product 34/2.webp','assets/products/Product 34/3.webp','assets/products/Product 34/4.webp','assets/products/Product 34/5.webp','assets/products/Product 34/6.webp','assets/products/Product 34/7.webp','assets/products/Product 34/8.webp'],
    url: 'https://www.etsy.com/listing/4431136468/florence-quilt-coat-beginner-sewing'
  },
  {
    short: 'Wool Jacket II',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted jacket</li><li>Comprehensive step-by-step instruction booklet to guide your sewing guidance</li><li>Printable pattern pieces marked clearly for easy cutting and assembly</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><div class="pm-desc-text">Medium to heavy coat fabrics such as wool blends, bouclé, tweed, or other structured synthetics. Seam allowance already added: 1 cm.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 38/1.webp','assets/products/Product 38/2.webp','assets/products/Product 38/3.webp','assets/products/Product 38/4.webp','assets/products/Product 38/5.webp','assets/products/Product 38/6.webp','assets/products/Product 38/7.webp','assets/products/Product 38/8.webp','assets/products/Product 38/9.webp'],
    url: 'https://www.etsy.com/listing/4426111922/wool-jacket-sewing-pattern-beginner'
  },
  ]
};

window.SPA_DATA['vests.html'] = {
  heading: 'Vests',
  products: [
  {
    short: 'Quilted Vest',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the quilted vest</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Layers for all the sizes</li><li>Measures include sizes in cm &amp; in</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Suggestions</div><div class="pm-desc-text">Quilting cotton, flannel, sherpa, pre-quilted fabric, and more. Cottons or linens between 3–7 oz per square yard recommended. Knit fabrics with a lot of stretch are not recommended.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 15/1.webp','assets/products/Product 15/2.webp','assets/products/Product 15/3.webp','assets/products/Product 15/4.webp','assets/products/Product 15/5.webp','assets/products/Product 15/6.webp','assets/products/Product 15/7.webp','assets/products/Product 15/8.webp','assets/products/Product 15/9.webp'],
    url: 'https://www.etsy.com/listing/4464713439/quilted-vest-sewing-pattern-beginner'
  },
  {
    short: 'Jersey Puffer Vest',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the puffer vest</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li><li>Tutorial video: how to turn jersey into a puffer vest</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Features</div><ul class="pm-desc-list"><li>Beginner-friendly puffer vest design</li><li>Professional finish achievable with simple construction techniques</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 20/1.webp','assets/products/Product 20/2.webp','assets/products/Product 20/3.webp','assets/products/Product 20/4.webp','assets/products/Product 20/5.webp','assets/products/Product 20/6.webp','assets/products/Product 20/7.webp','assets/products/Product 20/8.webp'],
    url: 'https://www.etsy.com/listing/4450004963/jersey-puffer-vest-sewing-pattern'
  },
  ]
};

window.SPA_DATA['blouses.html'] = {
  heading: 'Blouses',
  products: [
  {
    short: 'Side Tie Tank Blouse',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the blouse</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Finishing Options</div><div class="pm-desc-text">Option A: fully lined · Option B: facing finish</div></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><ul class="pm-desc-list"><li>1.4 yds main fabric (min 46" wide)</li><li>1.4 yds lining fabric — Option A, or 0.4 yds facing — Option B</li><li>Fusible interfacing (optional)</li><li>Invisible zipper min 21"/55 cm + invisible zipper foot</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 14/1.webp','assets/products/Product 14/2.webp','assets/products/Product 14/3.webp','assets/products/Product 14/4.webp','assets/products/Product 14/5.webp','assets/products/Product 14/6.webp','assets/products/Product 14/7.webp','assets/products/Product 14/8.webp'],
    url: 'https://www.etsy.com/listing/4476610444/side-tie-tank-blouse-sewing-pattern'
  },
  {
    short: 'Sleeveless Blouse',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the blouse</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Finishing Options</div><div class="pm-desc-text">Option A: fully lined · Option B: facing finish</div></div><div class="pm-desc-block"><div class="pm-desc-label">Materials Needed</div><ul class="pm-desc-list"><li>1.4 yds main fabric (min 46" wide)</li><li>1.4 yds lining fabric — Option A, or 0.4 yds facing — Option B</li><li>Fusible interfacing (optional)</li><li>Invisible zipper min 21"/55 cm + invisible zipper foot</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 40/1.webp','assets/products/Product 40/2.webp','assets/products/Product 40/3.webp','assets/products/Product 40/4.webp','assets/products/Product 40/5.webp','assets/products/Product 40/6.webp','assets/products/Product 40/7.webp','assets/products/Product 40/8.webp','assets/products/Product 40/9.webp','assets/products/Product 40/10.webp','assets/products/Product 40/11.webp','assets/products/Product 40/12.webp'],
    url: 'https://www.etsy.com/listing/4494575782/sleeveless-blouse-sewing-pattern'
  },
  {
    short: 'Evania Blouse',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Size Range</div><div class="pm-desc-text">XXS, XS, S, M, L, XL, 2XL, 3XL, 4XL, 5XL</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Detailed PDF sewing patterns to craft the blouse</li><li>Comprehensive step-by-step instruction booklet to guide your sewing journey</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Recommendations</div><div class="pm-desc-text">Lightweight woven fabrics with softness and drape — cotton lawn, voile, lightweight linen, or soft poplin. Sample is a linen blend, 140 gsm.</div></div><div class="pm-desc-block"><div class="pm-desc-label">Fabric Usage (View E)</div><div class="pm-desc-text">1.59–2.37 m (EU 34–54) · 1.74–2.59 yds (US 2/4–24) · Based on 140 cm / 55" wide fabric</div></div><div class="pm-desc-block"><div class="pm-desc-label">What You'll Receive</div><ul class="pm-desc-list"><li>US Letter printable pattern</li><li>A4 printable pattern</li><li>A0 printable pattern (print shop)</li><li>Detailed instruction manual with fabric recommendations, dimensions, pattern assembly instructions, and sewing guidance</li></ul></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 41/1.webp','assets/products/Product 41/2.webp','assets/products/Product 41/3.webp','assets/products/Product 41/4.webp','assets/products/Product 41/5.webp','assets/products/Product 41/6.webp','assets/products/Product 41/7.webp','assets/products/Product 41/8.webp'],
    url: 'https://www.etsy.com/listing/4498251678/evania-blouse-sewing-pattern-confident'
  },
  ]
};

window.SPA_DATA['pants.html'] = {
  heading: 'Pants',
  products: [
  {
    short: 'Nova Pants',
    desc: `<div class="pm-desc-block"><div class="pm-desc-label">Sizes</div><div class="pm-desc-text">0–34 (24"–54" waist · 34"–65" hip)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Pattern Formats</div><div class="pm-desc-text">A4, US Letter, A0 (print shop friendly)</div></div><div class="pm-desc-block"><div class="pm-desc-label">Design Features</div><ul class="pm-desc-list"><li>High-waisted wide-leg trousers</li><li>Elastic waistband</li><li>Full length with elegant drape</li><li>Optional cargo pockets</li><li>Optional drawstring</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Included With Your Pattern</div><ul class="pm-desc-list"><li>Digital PDF sewing pattern — layered files (print only your size)</li><li>A4 &amp; US Letter print-at-home format</li><li>Large format A0/Copyshop file</li><li>Seam allowances included · cm &amp; in measurements</li><li>Step-by-step illustrated instruction booklet</li><li>Detailed YouTube tutorial video</li></ul></div><div class="pm-desc-block"><div class="pm-desc-label">Recommended Fabrics</div><div class="pm-desc-text">Wide variety of fabrics; cottons or linens between 3–9 oz per square yard are favorites.</div></div><div class="pm-desc-note">Quality Guarantee: Rigorously tested. Money Back Guarantee if unsatisfied.<br>Digital Product · Instant Download</div>`,
    imgs: ['assets/products/Product 16/1.webp','assets/products/Product 16/2.webp','assets/products/Product 16/3.webp','assets/products/Product 16/4.webp','assets/products/Product 16/5.webp','assets/products/Product 16/6.webp','assets/products/Product 16/7.webp','assets/products/Product 16/8.webp'],
    url: 'https://www.etsy.com/listing/4460905421/nova-pants-pdf-sewing-pattern-wide-leg'
  },
  ]
};

/* shop-all shares the same products as shop-all.html — all products from all categories */
window.SPA_DATA['shop-all.html'] = {
  heading: 'Shop All',
  products: window.SPA_DATA['jackets.html'].products.concat(
    window.SPA_DATA['vests.html'].products,
    window.SPA_DATA['blouses.html'].products,
    window.SPA_DATA['pants.html'].products
  )
};
